base/urls.py
from django.urls import path
from . import views

app_name = 'nuru'

urlpatterns = [
    path('', views.index, name='index'),
    path('gallery', views.gallery, name='gallery'),
    path('contact', views.message, name='contact'),
    path('contact/zoom<slug:zoomie>/', views.zoom, name='zoom'),
    path('events/', views.events, name='events'),
    path('events/<slug:event>', views.event, name='event'),
    path('about-us', views.about, name='about'),
    path('downloads', views.downloads, name='downloads'),
    path('download/<int:document_id>/', views.download_file, name='download-file'),
    path('suscribe/', views.suscribe, name='suscribe'),
    path('prayers', views.prayers, name='prayers'),
    path('donate', views.donate, name='donate'),
    path('update-mosque', views.update_mosque, name='update-mosque'),
    path('administrator-mailer', views.mailer, name='mailer'),

]

base/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser

# Create your models here.

class PrayerTime(models.Model):
    name = models.CharField(max_length=10)
    azan = models.CharField(max_length=10)
    prayer = models.CharField(max_length=10)
    icon = models.TextField()

    def __str__(self):
        return self.name
    

class Event(models.Model):
    name = models.CharField(max_length=50)
    start = models.DateTimeField()
    end = models.DateTimeField()
    venue = models.CharField(max_length=50)
    info = models.CharField(max_length=1000)
    picture = models.ImageField(blank=True, null=True, upload_to='media')
    slugger = models.SlugField()

    def __str__(self):
        return self.name
    

class Address(models.Model):
    number = models.CharField(max_length=20)
    street = models.CharField(max_length=50, blank=True, null=True)
    lga = models.CharField(max_length=50, blank=True, null=True)
    state = models.CharField(max_length=20)
    country = models.CharField(max_length=10)
    phone = models.CharField(max_length=20)
    email = models.CharField(max_length=50)
    days_active = models.CharField(max_length=50)
    longitude = models.FloatField()
    latitude = models.FloatField()    


    def __str__(self):
        return f'Mosque at {self.lga}'


class Service(models.Model):
    name = models.CharField(max_length=20)
    start = models.TimeField(null=True, blank=True)
    end = models.TimeField(null=True, blank=True)
    days = models.CharField(max_length=50, null=True, blank=True)


    def __str__(self):
        return f'{self.name} service.'
    
class Photo(models.Model):
    picture = models.ImageField(upload_to='media/photos')
    description = models.TextField()

    def __str__(self):
        return f'{self.description}'
    
class Email(models.Model):
    email = models.EmailField()
    first_name = models.CharField(max_length=50, default='Guest')


    def __str__(self):
        return self.email
    
class Message(models.Model):
    title = models.CharField(max_length=50)
    message = models.TextField()
    email = models.EmailField()

    def __str__(self):
        return f'Message from {self.email} on {self.title}'
    
class Mosque(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    mosque = models.ForeignKey(Address, on_delete=models.CASCADE, default=1)
    zoom = models.FloatField(default=10.00)
    from_zoom = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.user.username} mosque object'

class MosqueName(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
class Leader(models.Model):
    name = models.CharField(max_length=50)
    position = models.CharField(max_length=50)
    picture = models.ImageField(upload_to='media/photos')
    bio = models.TextField()

    def __str__(self):
        return f'{self.position} {self.name}'
    
class Download(models.Model):
    name = models.CharField(max_length=50)
    about = models.TextField()
    file = models.FileField(upload_to='documents')

    def __str__(self):
        return self.name
    
class BankAccount(models.Model):
    account_name = models.CharField(max_length=50)
    account_number = models.CharField(max_length=11)
    bank_name = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.bank_name} account'
    
class Mailer(models.Model):
    email = models.EmailField()
    password = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.email} email'
    
class MailError(models.Model):
    email = models.EmailField()
    error = models.TextField()

    def __str__(self):
        return f'Failed to send to {self.email}'

base/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
import smtplib
from django.core.mail import send_mail
from datetime import datetime
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
# Create your views here.

def send_email(subject, from_email, mail_adds, message):
    subject = subject
    from_email = from_email
    to_email = mail_adds
    message = message
    
    # Prepare the plain text and HTML content
    

    # Create the email
    for mails, firstName in mail_adds.items():
        text_content = 'This is an important message.'
        html_content = render_to_string('base/email.html', {'first_name': firstName, 'body':message})
        email = EmailMultiAlternatives(subject, text_content, from_email, [mails])
        email.attach_alternative(html_content, "text/html")
    
    # Send the email
        try:

            email.send()
        except Exception as e:
            MailError.objects.create(email = mails, error = e)


def index(request):
    prayer_times = PrayerTime.objects.all()
    events = Event.objects.order_by('start')
    main = events.first()
    events = events.exclude(id = main.id)
    events = events[:3]
    addresses = Address.objects.all()
    services = Service.objects.all()
    photos = Photo.objects.all().order_by('?')
    num = len(photos)
    context = {'prayer_time':prayer_times, 'events':events, 'main':main, 'addresses':addresses, 'services':services, 'photos':photos, 'num':num}
    return render(request, 'base/index.html', context)


def gallery(request):
    addresses = Address.objects.all()
    services = Service.objects.all()
    photos = Photo.objects.all().order_by('?')
    first = photos.first()
    context = {'addresses':addresses, 'services':services, 'photos':photos, 'first': first}
    return render(request, 'base/gallery.html', context)

def message(request):
    ip = request.META.get('HTTP_X_FORWARDED_FOR')
    if ip:
        ip = ip.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    try:
        user = User.objects.get(username = ip)
    except(User.DoesNotExist):
        user = User.objects.create(username = ip)
    if request.method == 'POST':
        title = request.POST['title']
        message = request.POST['message']
        email = request.POST['email']
        new_message = Message.objects.create(title = title, message = message, email =  email)
        new_message.save()
        msg = 'Your message was sent successfully. Someone would get back to you as soon as possible.'
        addresses = Address.objects.all()
        services = Service.objects.all()
        try:
            mosque = Mosque.objects.get(user = user)
        except(KeyError, Mosque.DoesNotExist):
            mosque = Mosque.objects.create(user = user)
            mosque.save()
        mosque.from_zoom = False
        mosque.save()

        context = {'msg': msg, 'addresses':addresses, 'services':services, 'mosque': mosque}
        return render(request, 'base/message.html', context)
    else:
        addresses = Address.objects.all()
        services = Service.objects.all()
        try:
            mosque = Mosque.objects.get(user = user)
        except(KeyError, Mosque.DoesNotExist):
            mosque = Mosque.objects.create(user = user)
            mosque.save()
        
        mosque.from_zoom = False
        mosque.save()
    

        context ={'addresses':addresses, 'services':services, 'mosque': mosque}
        return render(request, 'base/message.html', context)


    
def zoom(request, zoomie):
    ip = request.META.get('HTTP_X_FORWARDED_FOR')
    if ip:
        ip = ip.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    try:
        user = User.objects.get(username = ip)
    except(User.DoesNotExist):
        user = User.objects.create(username = ip)

    try:
        mosque = Mosque.objects.get(user = user)
    except(KeyError, Mosque.DoesNotExist):
        mosque = Mosque.objects.create(user = user)
        mosque.save()
        
    if zoomie == "plus" and mosque.zoom<20:
        mosque.zoom = mosque.zoom + 0.5
        mosque.from_zoom = True
        mosque.save()
        addresses = Address.objects.all()
        services = Service.objects.all()
        context ={'addresses':addresses, 'services':services, 'mosque': mosque}
        return render(request, 'base/message.html', context)
  
   
    if zoomie =="minus" and mosque.zoom >1:
        mosque.zoom= mosque.zoom - 0.5
        mosque.from_zoom = True
        mosque.save()
        addresses = Address.objects.all()
        services = Service.objects.all()
        context ={'addresses':addresses, 'services':services, 'mosque': mosque}
        return render(request, 'base/message.html', context)
    else:
        err="MINIMUM/MAXIMUM ZOOM ACHIEVED"
        addresses = Address.objects.all()
        services = Service.objects.all()
        mosque = Mosque.objects.get(user = request.user)
        mosque.from_zoom = False
        mosque.save()

        context ={'addresses':addresses, 'services':services, 'mosque': mosque, 'err':err}
        return render(request, 'base/message.html', context)


def events(request):
    addresses = Address.objects.all()
    services = Service.objects.all()
    events = Event.objects.order_by('start')
    main = events.first()
    events = events.exclude(id = main.id)
        
    context = {'addresses':addresses, 'services':services, 'main':main, 'events':events}
    return render(request, 'base/events.html', context)

def event(request, event):
    addresses = Address.objects.all()
    services = Service.objects.all()
    event = Event.objects.get(slugger = event)

    context = {'addresses':addresses, 'services':services, 'event':event}
    return render(request, 'base/event.html', context)

def about(request):
    mosque_name = MosqueName.objects.first()
    addresses = Address.objects.all()
    services = Service.objects.all()
    leaders = Leader.objects.all().order_by('?')

    context = {'addresses':addresses, 'services':services,'name':mosque_name, 'leaders':leaders}
    return render(request, 'base/about.html', context)

def downloads(request):
    mosque_name = MosqueName.objects.first()
    addresses = Address.objects.all()
    services = Service.objects.all()
    files = Download.objects.all()

    context = {'addresses':addresses, 'services':services,'name':mosque_name, 'files':files}
    return render(request, 'base/downloads.html', context)



def download_file(request, document_id):
    document = get_object_or_404(Download, id=document_id)
    response = HttpResponse(document.file, content_type='application/octet-stream')
    response['Content-Disposition'] = f'attachment; filename="{document.file.name}"'
    return response



def suscribe(request):
    if request.method == 'POST':
        email = request.POST['email']
        name = request.POST['name']
        emails = Email.objects.all()
        for e in emails:

            if email == e.email:
                err = 'Already suscribed'
                prayer_times = PrayerTime.objects.all()
                events = Event.objects.order_by('start')
                main = events.first()
                events = events.exclude(id = main.id)
                events = events[:3]
                addresses = Address.objects.all()
                services = Service.objects.all()
                photos = Photo.objects.all().order_by('?')
                num = len(photos)
                context = {'err':err,'prayer_time':prayer_times, 'events':events, 'main':main, 'addresses':addresses, 'services':services, 'photos':photos, 'num':num}
                return render(request, 'base/index.html', context)
            
        new_email_obj = Email.objects.create(email = email, first_name= name)
        adds = {f'{new_email_obj.email}': f'{new_email_obj.first_name}'}
        send_email(subject='Welcome to Allahu Nuru Ala Nuru. We are thrilled to have you onboard.', from_email='hello@allahunurualanuru.com', mail_adds=adds, message="As a subscriber, you’ll be the first to know about our latest updates, exclusive offers, and insightful content tailored just for you. Our mission is to bring you the best in innovative solutions, community events and a sense of spiritual purpose. We’re excited to share this journey with you. \n Feel free to explore our website, and don’t hesitate to reach out with any questions or feedback. We value your input and are here to help! \n\nThank you for joining us. Let’s make great things happen together!")
        prayer_times = PrayerTime.objects.all()
        events = Event.objects.order_by('start')
        main = events.first()
        events = events.exclude(id = main.id)
        events = events[:3]
        addresses = Address.objects.all()
        services = Service.objects.all()
        photos = Photo.objects.all().order_by('?')
        num = len(photos)
        msg = 'Suscribed'

        context = {'msg':msg,'prayer_time':prayer_times, 'events':events, 'main':main, 'addresses':addresses, 'services':services, 'photos':photos, 'num':num}
        return render(request, 'base/index.html', context)


def prayers(request):
    addresses = Address.objects.all()
    services = Service.objects.all()
    
    context = {'addresses':addresses, 'services':services}
    return render(request, 'base/prayers.html', context)

def donate(request):
    addresses = Address.objects.all()
    services = Service.objects.all()
    accs = BankAccount.objects.all()
    
    context = {'addresses':addresses, 'services':services, 'accs':accs}
    return render(request, 'base/donate.html', context)

def update_mosque(request):
    ip = request.META.get('HTTP_X_FORWARDED_FOR')
    if ip:
        ip = ip.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    try:

base/templates/base/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>ALLAHU NURU ALA NURU

  </title>
  <meta name="description"
    content="Visit our head mosque at Shonle Ikorodu and discover our other two locations dedicated to community and worship.">
  <link rel="canonical" href="https://allahunurualanuru.com">
  <meta name="robots" content="index, follow">

  <!--Open Graph and twitter optimizations-->

  <meta property="og:title" content="Allahu Nuru Ala Nuru Shonle Mosque - Main Branch">
  <meta property="og:description" content="Connecting our community with three branches for worship and fellowship.">
  <meta property="og:image" content="{% static 'images/moon.jpg' %}">

  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="Allahu Nuru Ala Nuru Prayer Forum">
  <meta name="twitter:description" content="Experience the strength of faith and community at the Allahu Nuru Ala Nuru Islamic Prayer Forum. Our mission is to cultivate an enlightened Muslim society grounded in a genuine understanding of Islam, fostering spiritual growth and promoting the welfare of all humanity.">
  <meta name=" twitter:image" content="{% static 'images/moon.jpg' %}">

  <script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "WebSite",
      "name": "ALLAHU NURU ALA NURU ISLAMIC PRAYER FORUM",
      "url": "https://www.allahunurualanuru.com"
    }
    </script>
    




  <link rel="icon" href="{% static 'images/moon.jpg' %}" type="image/x-icon">



  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link href="{% static 'css/base.css' %}" rel="stylesheet" />
</head>


<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <div class="mosque_logo">
    <a class="navbar-brand" href="{% url 'nuru:index' %}">
      <img src="{% static 'images/moon.jpg' %}" alt="">
    </a>
  </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'nuru:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'nuru:gallery' %}">Gallery</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Explorer
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'nuru:events' %}">Events</a></li>
            <li><a class="dropdown-item" href="{% url 'nuru:contact' %}">Contact</a></li>
            <li><a class="dropdown-item" href="{% url 'nuru:about' %}">About Us</a></li>

            <li>
              <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="{% url 'nuru:downloads' %}">
                Downloads
                <!--Remember you'd need icons here...-->
              </a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="btn btn-block donate" aria-disabled="true" href="{% url 'nuru:donate' %}">Donate</a>
        </li>
      </ul>
      <div id="google_translate_element"></div>

    </div>
  </div>
</nav>


<body>
  {% block content %}
  {% endblock %}
  <!--Footer starting-->


  <div class="">
    <footer class="py-5">
      <div class="row admin">
        <div class="col-6 col-md-2 mb-3">
          <h5>Administrative Contact(s)</h5>


          {% for add in addresses %}
          <p class="black">
            {{add.number}},
            {% if add.street %}
            {{add.street}},
            {% endif %}
            <br>
            {% if add.lga %}
            {{add.lga}} LGA
            {% endif %}

            , <br> {{add.state}} State,<br> {{add.country}} <br>{{add.phone}} <br> {{add.email}} <br>{{add.days_active}}
          </p>
          {% endfor %}

        </div>



        <div class="col-6 col-md-2 mb-3">
          <h5>Quick links</h5>
          <ul class="nav flex-column">
            <li class="nav-item mb-2"><a href="{% url 'nuru:index' %}" class="nav-link p-0 text-muted">Home</a></li>
            <li class="nav-item mb-2"><a href="{% url 'nuru:gallery' %}" class="nav-link p-0 text-muted">Photo
                Gallery</a></li>
            <li class="nav-item mb-2"><a href="{% url 'nuru:contact' %}" class="nav-link p-0 text-muted">Contact Us</a>
            </li>
            <li class="nav-item mb-2"><a href="{% url 'nuru:events' %}" class="nav-link p-0 text-muted">Events</a></li>
            <li class="nav-item mb-2"><a href="{% url 'nuru:downloads' %}" class="nav-link p-0 text-muted">Downlaods</a>
            </li>
            <li class="nav-item mb-2"><a href="{% url 'nuru:about' %}" class="nav-link p-0 text-muted">About</a></li>

          </ul>
        </div>




        <div class="col-6 col-md-2 mb-3">
          <h5>Our Services</h5>
          <p>
            We invite you to worship with us.
          </p>
          <ul class="nav flex-column">
            {% for s in services %}
            <li class="nav-item mb-2 black">

              {{s.name}} <br>

              {% if s.start %}
              {{s.start}} -
              {% endif %}

              {% if s.end %}
              {{s.end}} <br>
              {% endif %}

              {{s.days}}

            </li>
            {% endfor %}

          </ul>
        </div>

        <div class="col-md-5 offset-md-1 mb-3">
          <form method="post" action="{% url 'nuru:suscribe' %}">
            {% csrf_token %}
            <h5>Subscribe to our newsletter</h5>
            <p class="black">
              Get updates and highlights of new and exciting resources to support your spiritual growth.
            </p>
            <div class="d-flex flex-column flex-sm-row w-100 gap-2">
              <input type="text" placeholder="Enter your name"  class="form-control" name="name"> <br>

              <label for="newsletter1" class="visually-hidden">Email address</label>
              <input id="newsletter1" type="text" class="form-control" placeholder="Email address" name="email">
              <button class="btn btn-primary" type="submit">Subscribe</button>
            </div>
          </form>
        </div>
      </div>


    </footer>

  </div>


  <!--Footer ending-->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
  <script src="{% static 'scripts/base.js' %}"></script>
</body>


<script type="text/javascript">
  function googleTranslateElementInit() {
    new google.translate.TranslateElement({ pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.SIMPLE }, 'google_translate_element');
  }
</script>
<script type="text/javascript"
  src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>


</html>

base/templates/base/index.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
{% if err %}
<script>
    alert('Already suscribed')
</script>
<p style="color: white; text-align: center; background-color: red;">
    {{err}}
</p>
{% endif %}

{% if msg %}
<script>
    alert('Welcome! You\'re officially on our list!!!')
</script>
<p style="color: white; background-color: green; text-align: center;">
    You're officially on our list!!!
</p>
{% endif %}
<div>



    <!--Green in the name div-->
    <div class="row">


        <!--Two cols-->


        <div class="col">
            <h1>
                Welcome to Allahu Nuru Ala Nuru Islamic Prayer Forum.
            </h1> <br>
            <hr>
            <p>
                Experience the strength of faith and community at the Allahu Nuru Ala Nuru Islamic Prayer Forum. Our
                mission is to cultivate an enlightened
                Muslim society grounded in a genuine understanding of Islam, fostering spiritual growth and promoting
                the welfare of all humanity. <br>


                Allahu Nuru Ala Nuru Islamic Prayer Forum was established on the first Thursday of February 2013 at
                Shonle along Imowonla Road, starting with just seven members.
            </p>

            <a href="{% url 'nuru:about' %}" class="join">Read about us.</a>

        </div>


        <div class="col">
            <img style="width: 100%;" src="{% static 'images/praying.jpg' %}" alt="">


        </div>




    </div>
    <!--Green in the name div-->



    <!--Prayer times section-->

    <div class="ptime">
        <div class="ptimehead">
            <h2>
                Prayer Timetable

            </h2>
        </div>
    </div>


    <div class="ptable">




        <div class="prow">


            <div class="col">

                <h3>
                    Worship with us in the name of Allah, creator of the universe.
                </h3>

                <b>
                    In Islam, prayer (Salah) is a core act of worship, observed five times daily at designated times.
                    These prayer times are determined by the position of the sun and vary according to geographic
                    location and season.
                </b> <br>
                <hr>
                <p>


                    <a href="{% url 'nuru:prayers' %}" class="join">
                        Read more
                    </a>



                </p>


            </div>


            <div class="col">

                <table>

                    <thead>
                        <tr>
                            <th>
                                Salat
                            </th>
                            <th>
                                Azan
                            </th>
                            <th>
                                Prayer
                            </th>
                        </tr>
                    </thead>

                    <tbody>



                        {% for pt in prayer_time %}
                        <tr>
                            <td>

                                {{pt.icon|safe}}


                                {{pt.name}}
                            </td>
                            <td>
                                {{pt.azan}} </td>
                            <td>
                                {{pt.azan}} </td>
                        </tr>

                        {% endfor %}

                    </tbody>

                </table>


            </div>



        </div>

    </div>

    <div class="services">
        <h2 style="text-align: center;">
            Our sercive hours.
        </h2>
        <p style="padding-left: 50px;">
            Come and worship with us
        </p>
        <table>
            <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Start Time
                    </th>
                    <th>
                        End Time
                    </th>
                    <th>
                        Days Scheduled
                    </th>
                </tr>

            </thead>

            <tbody>
                {% for s in services %}
                <tr>
                    <td>
                        {% if s.name %}
                        {{s.name}}
                        {% else %}
                        -
                        {% endif %}
                    </td>
                    <td>
                        {% if s.start %}
                        {{s.start}}
                        {% else %}
                        -
                        {% endif %}
                    </td>
                    <td>
                        {% if s.end %}
                        {{s.end}}
                        {% else %}
                        -
                        {% endif %} </td>
                    <td>
                        {% if s.days %}
                        {{s.days}}
                        {% else %}
                        -
                        {% endif %} </td>
                </tr>

                {% endfor %}

            </tbody>
        </table>
    </div>

    <!--Prayer times section-->

    <!--Events and upcoming community activities-->
    <h3 style="text-align: center; text-decoration: underline;">
        Upcoming events and community activities.
    </h3>
    <p class="join-us">

        Join Us for Upcoming Events at the Mosque! <br>

        We invite you to explore our website for a list of exciting upcoming events and community activities.
        Whether you're looking to deepen your understanding of our faith, connect with fellow community members, or
        participate in family-friendly activities, there's something for everyone! <br>

        Don't miss out on our special gatherings, educational programs, and volunteer opportunities. Visit our <a
            href="{% url 'nuru:events' %}">events</a>
        page today and be part of our vibrant community! <br>

        We look forward to welcoming you!


    </p> <br>
    <a href="{% url 'nuru:event' main.slugger %}" style="text-decoration: none; color: black;">
        <h4 style="text-align: center;">
            {{main.name}}
        </h4> <br />
        <p style="text-align: center;">
            Venue: {{main.venue}}
        </p>
        <br>
        <div class="emain">

            <img style="width: 100%;" src="{{main.picture.url}}" alt="{{main.info}}">

        </div>
    </a>

    <div class="erow">






        {% for e in events %}
        <div class="ecol"
            style="background-image: url({{e.picture.url}}); padding: 10%; background-repeat: no-repeat; background-size: contain;">

            <a href="{% url 'nuru:event' e.slugger %}" style="text-decoration: none; color: black;">


                <b> {{e.name}}</b> <br>
                Venue: {{e.venue}}
            </a>
            </a>


        </div>
        {% endfor %}
        <a href="{% url 'nuru:events' %}">More events.</a>


    </div>

    <!--End of events and upcoming activities-->

    <!--Photo gallery division-->
    <h3 style="text-align: center; margin-top: 20px;">
        Photo gallery
    </h3>

    <div>



        <div class="prow">

            {% for p in photos|slice:"0:5" %}


            <div class="pcol">
                <img style="width: 100%; height: 100%; cursor: pointer;" onclick="showImg(this.src, this.alt)"
                    src="{{p.picture.url}}" alt="{{p.description}}">
            </div>

            {% endfor %}


        </div>




        <div class="prow2">

            {% for p in photos|slice:"6:9" %}


            <div class="pcol2">
                <img style="width: 100%; height: 100%; cursor: pointer;" src="{{p.picture.url}}"
                    onclick="showImg(this.src, this.alt)" src="{{p.picture.url}}" alt="{{p.description}}">
            </div>

            {% endfor %}



            <div class="pcol2" style="position: relative;">
                <a href="{% url 'nuru:gallery' %}">

                    <img style="width: 100%; height: 100%;" src="{% static 'images/more.png' %}" alt="">
                    <p class="num">
                        {{num}}
                    </p>
                </a>

            </div>

            <div class="full-img" id="fullImgBox">
                <span onclick="hideImg()">
                    X
                </span>
                <img src="{{first.picture.url}}" id="fullImg" alt="">
                <p id="caption">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam, odit! Eveniet et, dolores non
                    beatae deleniti
                    fugiat quibusdam vitae debitis aperiam fugit quasi sint odit dolore ullam ipsum atque natus.
                </p>
            </div>


        </div>


    </div>

    <!--End of photo gallery div-->


</div>
<script src="{% static 'scripts/base.js' %}"></script>
{% endblock %}

base/templates/base/signup.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
{% endblock %}